### ISSUE TITLE
オプションで指定するユーザー名やSSM有効無効のデフォルト値を変更したい

### ISSUE THREAD

**Issue by IMJ-koji-hiyama** [tomozo6/ec2ssh#3]
コンフィグファイルまたはデフォルトの書き換えコマンドなどでオプションのデフォルト値を変更したいです。

**Comment by tomozo6** [comment]
@IMJ-koji-hiyama 
全面的に刷新しました。(ShellからGoに変更)
刷新にあたりConfigファイルも読み込めるようにしました。

ec2sshのバージョンカウントもやり直したいため、一度アンインストールしてから再度インストールをしてみてください。

```bash
brew uninstall ec2ssh
brew install ec2ssh
```
